### ISSUE TITLE
VSCode: When the same file is open in multiple editors clicking a comment navigates in wrong editor

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#109]
If I split the view in VSCode and have two editors open to the same file when I click on a comment in CodeStream it jumps to the comment in the wrong editor. I would expect it to use the last active editor but it appears to use a random one. 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.1.3
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by eamodio** [comment]
This will be resolved in the next CodeStream release. Thanks for the report!

**Comment by planteater** [comment]
Fixed in v3.0

**Comment by AndrewMorsillo** [comment]
Hi @planteater I tested this in v3.0 and it's still broken. If I open the same file in two editor groups then click a code mark it seems to pick a random editor to navigate to that line instead of the last focused editor.

**Comment by planteater** [comment]
I think we got this one for real this time, in v3.0.1
