### ISSUE TITLE
PHPStorm Cannot Checkout GitLab Branch From Merge Requests

### ISSUE THREAD

**Issue by s1rc** [TeamCodeStream/codestream#502]
Very similar to this issue https://github.com/TeamCodeStream/codestream/issues/348 except for the rate limiting.

Opening a MR from our GitLab instance the "Check out branch" button is disabled, hovering over the button shows a message:
```
Checkout Branch
Disabled: You don't have the XXXX repo open in your IDE
```

The repository is open in PHPStorm Git window. I've tried both ssh and https access to the repository remotes, renaming the remotes, nothing helps.

**Comment by planteater** [comment]
@s1rc - Could I trouble you for a log file? Reproduce the issue and then in your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

If you'd prefer not to post it here, you can send it to me at support@codestream.com. Thanks!

**Comment by s1rc** [comment]
@planteater I have emailed the `idea.log` file to that email address.

**Comment by PatentLobster** [comment]
I have that same issue, in my log I can see that the repo has two remotes in codestream somehow and one of them is wrong

**Comment by planteater** [comment]
@PatentLobster - A fix for this should be available in our next release. Sometime in the next couple of days.

**Comment by planteater** [comment]
Fixed in v11.0.4.

**Comment by PatentLobster** [comment]
@planteater Just updated this is not fixed yet, in the debugging output I can see the repo has two remotes, one of them wrong and codestream uses the wrong one.

**Comment by planteater** [comment]
@PatentLobster - Could I trouble you to do a `git remote -v` for that repo and email the output to support@codestream.com? I'll need your email address anyway to look up your account, so best to email rather than post here. Thanks!
